### ISSUE TITLE
pip install hcipy not complete?

### ISSUE THREAD

**Issue by NuggetOfficial** [ehpor/hcipy#218]
Hey ho,

I am working on a package that uses hcipy as a dependency. When I `pip install hcipy` all is well, but when I try to import it in a python file I run into the following traceback:

```
Traceback (most recent call last):
  File "<redacted>", line 1, in <module>
    import hcipy
  File "<redacted>\hcipy\__init__.py", line 5, in <module>
    from . import atmosphere
  File "<redacted>\hcipy\atmosphere\__init__.py", line 18, in <module>
    from .atmospheric_model import *
  File "<redacted>\hcipy\atmosphere\atmospheric_model.py", line 3, in <module>
    from ..optics import OpticalElement
  File "<redacted>\hcipy\optics\__init__.py", line 66, in <module>
    from .aberration import *
  File "<redacted>\hcipy\optics\aberration.py", line 4, in <module>
    from ..util import SpectralNoiseFactoryFFT, inverse_tikhonov
  File "<redacted>\hcipy\util\__init__.py", line 30, in <module>
    from .io import *
  File "<redacted>\hcipy\util\io.py", line 6, in <module>
    import asdf.fits_embed
ModuleNotFoundError: No module named 'asdf.fits_embed'
```

How do I fix this? I did not run into this error before. 
My python version is 3.11.4

**Comment by ehpor** [comment]
@NuggetOfficial Yes, the current pip install is broken due to the removal of fits_embed in asdf 3.0.0. And I haven't gotten to making a new release yet, since there is still 1-2 PRs that need to be finished before then.

The fix for HCIPy was made in https://github.com/ehpor/hcipy/pull/199 and will be in the new release. A simple workaround for now is to use the dev version (not recommended, unless you need any new features), or install asdf 2.15.1 instead of asdf 3.0.0.

**Comment by NuggetOfficial** [comment]
worked like a charm!
