### ISSUE TITLE
Fibers and microlens arrays

### ISSUE THREAD

**Issue by NuggetOfficial** [ehpor/hcipy#235]
Im running into a bit of an issue when working with fibers and microlensarrays.
Here are my versions
| pkgs | version |
|----|----|
| nixOS (linux) | 2.18.5 |
| python | 3.12.5 |
| hcipy | 0.6.0 |

Im running the following code:
```python
from matplotlib import pyplot as plt
from hcipy import *

def main():
    pupil = make_pupil_grid(512)
    aper = make_rectangular_aperture(0.9)(pupil)
    fibers = make_uniform_grid(3, [0.3,0.3])
    
    imshow_field(aper)
    plt.show()

    wf = Wavefront(aper, input_stokes_vector=[1,0,0,0])
    
    smfa = SingleModeFiberArray(pupil, fibers, make_gaussian_fiber_mode(1))
    fed_smfa = smfa.forward(wf)

    imshow_field(fed_smfa.I)
    plt.show()

    mla = MicroLensArray(pupil, fibers, 40)
    mla_overlay=mla.forward(fed_smfa)
    
    imshow_field(mla_overlay.I)
    plt.show()

    focus = make_focal_grid(6,30)
    prop  = FraunhoferPropagator(pupil, focus)
    mla_foc = prop.forward(mla_overlay)

    imshow_field(mla_foc.I)
    plt.show()

    return 0

if __name__ == "__main__":
    main()
```
Im running a test where I try to feed a wavefront into a `SingleModeFiberArray` which then gets manipulated by a `MicroLensArray`. The idea is that I see each fiber seperately in focus at mla_foc. Either I do not understand how to use these Optics (most likely) or there is something more fundamental going wrong because I keep running into shape errors.

right now I'm stuck on the following traceback:
```
Traceback (most recent call last):
  File (redacted)/hcipy_test_implementation.py", line 36, in <module>
    main()
  File "(redacted)/hcipy_test_implementation.py", line 15, in main
    fed_smfa = smfa.forward(wf)
               ^^^^^^^^^^^^^^^^
  File "(redacted)/python3.12/site-packages/hcipy/optics/fiber.py", line 331, in forward
    res = self.projection_matrix.T.dot(wavefront.electric_field.conj() * self.input_grid.weights)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: shapes (9,262144) and (2,2,262144) not aligned: 262144 (dim 1) != 2 (dim 1)
```
As per #73 I tried to look at the shack-hartmann sensor for some answers but I'm till stuck as to whats happening.
Can I get some help getting this to work?
cheers,
Tom

**Comment by syhaffert** [comment]
The shapes of the micro-lens array and the fibers don't match. Are you using a polarized wavefront? Your electric field has a (2,2,N) tensor shape.

**Comment by NuggetOfficial** [comment]
I am using a polarized wavefront, removing the `input_stokes_vector` now gets  me through the `SingleModeFiberArray`. This is my current output after shrinking the field mode diameter quite substantially (to 0.001) and switching to a 5x5 grid of fibers.
![image](https://github.com/user-attachments/assets/1a6f34e8-4462-49ea-9d0e-14f52b6eae0b)

Am I correct in understanding that each spaxel I see in the forwarded field encodes a fiber? I would assume with the rectangular input wavefront that they would all be equally illuminated? Or am I seeing an acceptance angle effect here and I should feed the fibers using multiple phase ramps?

I am now getting the following traceback at the mla.
```
Traceback (most recent call last):
  File "(redacted)/hcipy_test_implementation.py", line 36, in <module>
    main()
  File "(radacted)/hcipy_test_implementation.py", line 21, in main
    mla_overlay=mla.forward(fed_smfa)
                ^^^^^^^^^^^^^^^^^^^^^
  File "(redacted)/python3.12/site-packages/hcipy/optics/micro_lens_array.py", line 54, in forward
    return self.mla_surface.forward(wavefront)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "(redacted)/python3.12/site-packages/hcipy/optics/optical_element.py", line 758, in res
    return forward(self, instance_data, wavefront, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "(redacted)/python3.12/site-packages/hcipy/optics/apodization.py", line 41, in forward
    wf.electric_field *= instance_data.apodization
ValueError: operands could not be broadcast together with shapes (25,) (262144,) (25,)
```
I'm sorry if the mistake seems obvious, I got lost in the HCIpy sauce.

**Comment by syhaffert** [comment]
What you are seeing is the PSF profile that you feed into the system. Unless you have a flat wavefront entering the fiber.

The error is correct. The output of the SingleModeFiberArray is an array of complex amplitudes for each fiber. This is an array of modal coefficients. The electric field as function of position is not an output.

**Comment by NuggetOfficial** [comment]
So what the plot shows is not the electric field as a function of position but rather 25 descriptions of the complex fiber output. So say i would like to now focus the light coming out of the fiber with a lenslet; how should I achieve this?  The `Apodizer` prescription requires `E(x,y)` if im not mistaken?

**Comment by ehpor** [comment]
@NuggetOfficial Since the `SingleModeFiberArray` class is to propagate from free space to the guided modes of a SMF array, you'd need to propagate backwards from there. So backwards through a fiber array (potentially a different object with different parameters for the fibers) and then a Fresnel propagation, then the microlens array itself.
